parameters:
#    tusk_redis_queue.example.class: Tusk\RedisQueueBundle\Example

services:
#    tusk_redis_queue.example:
#        class: %tusk_redis_queue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tusk_redis_queue.connection_abstract:
        class:    Tusk\RedisQueue\Connection
        abstract: true
