parameters:
    tusk_redis_queue.connection.class:  Tusk\RedisQueue\Connection
    tusk_redis_queue.producer.class:    Tusk\RedisQueue\Producer
    tusk_redis_queue.consumer.class:    Tusk\RedisQueue\Consumer
    tusk_redis_queue.rpc_factory.class: Tusk\RedisQueue\RpcFactory
    tusk_redis_queue.monitor.class:     Tusk\RedisQueue\Monitor
    
services: ~


