parameters:
    tusk_redis_mq.connection.class:  Tusk\RedisMq\Connection
    tusk_redis_mq.producer.class:    Tusk\RedisMq\Producer
    tusk_redis_mq.consumer.class:    Tusk\RedisMq\Consumer
    tusk_redis_mq.rpc_factory.class: Tusk\RedisMq\RpcFactory
    tusk_redis_mq.monitor.class:     Tusk\RedisMq\Monitor
    
services: ~


